# Generated by Django 4.1.11 on 2023-11-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartWarteg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeractuator',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dishcleaneractuator',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stovesafetyactuator',
            name='status',
        ),
        migrations.AddField(
            model_name='customeractuator',
            name='light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeractuator',
            name='monitor',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customeractuator',
            name='sound_alert',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='dishcleaneractuator',
            name='dish_cleaner_rotator',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dishcleaneractuator',
            name='dish_soap_pump',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='dishcleaneractuator',
            name='sink_water_valve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stovesafetyactuator',
            name='fire_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stovesafetyactuator',
            name='gas_exhaust',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stovesafetyactuator',
            name='light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stovesafetyactuator',
            name='monitor',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stovesafetyactuator',
            name='sound_alert',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='stovesafetyactuator',
            name='water_sprinkler',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
