# Generated by Django 4.1.11 on 2023-11-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartWarteg', '0002_remove_customeractuator_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeractuator',
            old_name='monitor',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='dishcleaneractuator',
            old_name='dish_cleaner_rotator',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='stovesafetyactuator',
            old_name='gas_exhaust',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='customeractuator',
            name='light',
        ),
        migrations.RemoveField(
            model_name='customeractuator',
            name='sound_alert',
        ),
        migrations.RemoveField(
            model_name='dishcleaneractuator',
            name='dish_soap_pump',
        ),
        migrations.RemoveField(
            model_name='dishcleaneractuator',
            name='sink_water_valve',
        ),
        migrations.RemoveField(
            model_name='stovesafetyactuator',
            name='fire_alarm',
        ),
        migrations.RemoveField(
            model_name='stovesafetyactuator',
            name='light',
        ),
        migrations.RemoveField(
            model_name='stovesafetyactuator',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='stovesafetyactuator',
            name='sound_alert',
        ),
        migrations.RemoveField(
            model_name='stovesafetyactuator',
            name='water_sprinkler',
        ),
    ]
